name: Deploy 2Tier Architecture

on:
    push:
        branches:
            - main

jobs:
    terraform:
        name: Deploy Infrastructure
        runs-on: ubuntu-latest

        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            TF_VAR_region: ${{ secrets.TF_VAR_REGION}}
            TF_VAR_username: ${{ secrets.TF_VAR_USERNAME}}
            TF_VAR_state_bucket: ${{ secrets.TF_VAR_STATE_BUCKET}}
            TF_VAR_table_name: ${{ secrets.TF_VAR_TABLE_NAME}}

        defaults:
            run:
                working-directory: ./terraform

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v2

            - name: Terraform Setup
              uses: hashicorp/setup-terraform@v1
              
            - name: Terraform Format
              run: terraform fmt
            
            - name: Terraform Init
              run: terraform init
            
            - name: Terraform Validate
              run: terraform validate
              
            - name: Terraform Plan
              run: terraform plan
              
            - name: Terraform Apply
              run: terraform apply -auto-approve  
                 #2024-09-06T00:16:47.748Z [DEBUG] backend/local: will prompt for input of unset required variables [public_subnet_1 public_subnet_2 az1 vpc_cidr private_subnet_2 ami engine_version private_subnet_1 instance_type db_username db_password az2 key_name instance_class]
##2024-09-06T00:16:47.749Z [DEBUG] command: asking for input: "var.ami"